name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]  # You can specify Node.js versions here

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3
      
      # Step 2: Cache node modules
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 3: Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run Tests (Optional, but recommended)
      #- name: Run Tests
       # run: npm test

      # Step 6: Build Application
      - name: Build Application and Run Unit Tests
        run: CI=false npm run build

      # Step 7: List build directory contents to verify build
      - name: List build directory contents
        run: ls -R build

      # Step 8: Configure AWS credentials and Sync to S3
      - name: Sync files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "build"   # The directory containing the built files
          AWS_S3_BUCKET: "mygablubacket"

      # Step 9: Verify sync by listing files in S3 (Optional)
      - name: Verify S3 sync
        run: aws s3 ls s3://mygablubacket/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
